networks:
  mysql:
    internal: true
  valkey:
    internal: true
secrets:
  db_password:
    file: './ops/secret'
  db_root_password:
    file: './ops/secret'
services:
  mysql:
    cap_drop:
      - 'ALL'
    command:
      - '--log-error-suppression-list="MY-013360"'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD_FILE: '/run/secrets/db_password'
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/db_root_password'
      MYSQL_USER: 'db'
    healthcheck:
      interval: '10s'
      retries: 3
      start_period: '30s'
      test:
        - 'CMD'
        - 'mysqladmin'
        - 'ping'
      timeout: '5s'
    image: 'mysql:8-oracle'
    logging:
      driver: 'json-file'
      options:
        max-file: 3
        max-size: '10m'
    networks:
      - 'mysql'
    read_only: true
    restart: 'unless-stopped'
    secrets:
      - 'db_password'
      - 'db_root_password'
    security_opt:
      - 'no-new-privileges:true'
    stop_grace_period: '60s'
    sysctls:
      - 'net.core.somaxconn=65535'
    ulimits:
      nofile:
        hard: 1048576
        soft: 1048576
    user: 'mysql:mysql'
    volumes:
      - target: '/tmp'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
      - target: '/run'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
      - source: 'mysql_data'
        target: '/var/lib/mysql'
        type: 'volume'
  valkey:
    cap_drop:
      - 'ALL'
    healthcheck:
      interval: '10s'
      retries: 3
      start_period: '30s'
      test:
        - 'CMD'
        - 'valkey-cli'
        - 'ping'
      timeout: '5s'
    image: 'valkey/valkey:9-trixie'
    logging:
      driver: 'json-file'
      options:
        max-file: 3
        max-size: '10m'
    networks:
      - 'valkey'
    read_only: true
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges:true'
    stop_grace_period: '60s'
    sysctls:
      - 'net.core.somaxconn=65535'
    ulimits:
      nofile:
        hard: 1048576
        soft: 1048576
    user: 'valkey:valkey'
    volumes:
      - target: '/tmp'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
      - target: '/run'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
      - source: 'valkey_data'
        target: '/data'
        type: 'volume'
volumes:
  mysql_data:
  valkey_data:
